### ISSUE TITLE
NaCl module crashed. Unmounted.

### ISSUE THREAD

**Issue by cbandy** [yoichiro/chromeos-filesystem-sftp#80]
SFTP File System 1.7.6

background page console:
```
background.js:1407 Object {type: "mount", serverName: "192.168.1.101", serverPort: "22", authType: "keyboard-interactive", username: "cbandy"…}authType: "keyboard-interactive"mountPath: "/Users/cbandy"password: "x"privateKey: ""serverName: "192.168.1.101"serverPort: "22"type: "mount"username: "cbandy"__proto__: Object
background.js:177 mountPath: /Users/cbandy
background.js:223 Object {message: "fingerprint", request: 0, values: Array[2]}
background.js:638 Object {requestId: 0, fingerprint: "a7d83eed2f146e67fcd717106ddda2e5", algorithm: "ssh-rsa"}
background.js:1407 Object {type: "accept", requestId: 0, fileSystemId: "sftpfs://192.168.1.101:22/cbandy"}
background.js:648 allowToConnect
_generated_background_page.html:1 NativeClient: NaCl module crashed
background.js:233 -1
background.js:721 onNaClModuleCrashed - -1
background.js:1074 doUnmount
background.js:1087 _doUnmount
background.js:1092 sftpfs://192.168.1.101:22/cbandy
background.js:1303 deleteTaskQueue: sftpfs://192.168.1.101:22/cbandy
background.js:1343 deleteMetadataCache: sftpfs://192.168.1.101:22/cbandy
extensions::lastError:133 Unchecked runtime.lastError while running fileSystemProvider.unmount: NOT_FOUND
    at null.<anonymous> (chrome-extension://gbheifiifcfekkamhepkeogobihicgmn/background.js:1093:43)
    at null.<anonymous> (chrome-extension://gbheifiifcfekkamhepkeogobihicgmn/background.js:1134:17)
```

ui_log:
```
[49,3057811456:02:12:39.123309] Native Client module will be loaded at base address 0x0000000000000000
SftpInstance::SftpInstance
SftpInstance::SftpInstance End
SftpInstance::HandleMessage
SftpInstance::HandleMessage connect 0
SftpThread::SftpThread
SftpInstance::HandleMessage SftpThread instance created
SftpThread::ConnectAndHandshake
SftpThread::ConnectAndHandshake Thread started
SftpInstance::HandleMessage End
SftpThread::ConnectAndHandshakeImpl
SftpThread::InitializeLibssh2
SftpThread::InitializeLibssh2 rc=0
SftpThread::ConnectToSshServer
SftpThread::ConnectToSshServer sock=3
SftpThread::ConnectToSshServer sockaddr_in ready
SftpThread::ConnectToSshServer rc=0
SftpThread::InitializeSession
SftpThread::InitializeSession Initialized session 
SftpThread::HandshakeSession
SftpThread::HandshakeSession rc=0
SftpThread::GetHostKeyHash
SftpThread::GetHostKeyHash hash=a7d83eed2f146e67fcd717106ddda2e5
SftpThread::GetHostKeyMethod
SftpThread::GetHostKeyMethod method=ssh-rsa
SftpInstance::OnHandshakeFinished
SftpInstance::SendResponseAsStringArray
SftpInstance::SendResponseAsStringArray End
SftpThread::ConnectAndHandshakeImpl End
SftpInstance::HandleMessage
SftpInstance::HandleMessage authenticate 0
SftpInstance::HandleMessage Re-use SftpThread instance
SftpThread::Authenticate
SftpThread::Authenticate Thread started
SftpInstance::HandleMessage End
SftpThread::AuthenticateImpl
SftpThread::AuthenticateUser
SftpThread::AuthenticateUser auth_list=publickey,keyboard-interactive
SftpThread::AuthenticateByKeyboardInteractive
** abort() called

** Signal 4 from untrusted code: pc=2632b0
[17069:17091:0501/211239:ERROR:nacl_process_host.cc(296)] NaCl process exited with status 64512 (0xfc00)
```

about:
```
Version 43.0.2357.46 beta
Platform 6946.31.0 (Official Build) beta-channel daisy
Firmware Google_Snow.2695.117.0

Currently on beta channel.

WebKit
537.36 (@c618a4adf8a986b6e968600d0dbcbb6cac93a6bf)

V8
4.3.61.14

User Agent
Mozilla/5.0 (X11; CrOS armv7l 6946.31.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.46 Safari/537.36

Command Line
/opt/google/chrome/chrome --ppapi-flash-path=/opt/google/chrome/pepper/libpepflashplayer.so --ppapi-flash-version=17.0.0.176-r1 --ppapi-flash-args=enable_hw_video_decode=1 --enable-fixed-position-compositing --enable-impl-side-painting --max-tiles-for-interest-area=512 --ui-enable-per-tile-painting --ui-prioritize-in-gpu-process --use-gl=egl --gpu-sandbox-failures-fatal=yes --gpu-sandbox-start-early --enable-logging --log-level=1 --use-cras --user-data-dir=/home/chronos --max-unused-resource-memory-usage-percentage=5 --login-profile=user --has-chromeos-keyboard --default-wallpaper-large=/usr/share/chromeos-assets/wallpaper/default_large.jpg --default-wallpaper-small=/usr/share/chromeos-assets/wallpaper/default_small.jpg --child-wallpaper-large=/usr/share/chromeos-assets/wallpaper/child_large.jpg --child-wallpaper-small=/usr/share/chromeos-assets/wallpaper/child_small.jpg --guest-wallpaper-large=/usr/share/chromeos-assets/wallpaper/guest_large.jpg --guest-wallpaper-small=/usr/share/chromeos-assets/wallpaper/guest_small.jpg --enterprise-enable-forced-re-enrollment --enterprise-enrollment-initial-modulus=13 --enterprise-enrollment-modulus-limit=17 --vmodule=screen_locker=1,webui_screen_locker=1,*ui/display/chromeos*=1,*ash/display*=1,*ui/ozone*=1,*zygote*=1,*plugin*=2 --login-manager

Build Date
Thursday, April 30, 2015
```

**Comment by yoichiro** [comment]
@cbandy Can this issue be reproduced using the latest version 1.7.8?

**Comment by zmyaro** [comment]
I am on v1.7.8 and still seeing this error on my Chromebook Pixel.

**Comment by Tjebbe80** [comment]
I have the same error here: NaCl module crashed. Unmounted. 

Asus Flip C100 
CromeOS version 45.0.2454.15 beta  
SFTP version 1.7.8

ui_log:
[1,3060281344:09:33:02.726853] Native Client module will be loaded at base address 0x0000000000000000
SftpInstance::SftpInstance
SftpInstance::SftpInstance End
SftpInstance::HandleMessage
SftpInstance::HandleMessage connect 0
SftpThread::SftpThread
SftpInstance::HandleMessage SftpThread instance created
SftpThread::ConnectAndHandshake
SftpThread::ConnectAndHandshake Thread started
SftpInstance::HandleMessage End
SftpThread::ConnectAndHandshakeImpl
SftpThread::InitializeLibssh2
SftpThread::InitializeLibssh2 rc=0
SftpThread::ConnectToSshServer
SftpThread::ConnectToSshServer sock=3
SftpThread::ConnectToSshServer sockaddr_in ready
SftpThread::ConnectToSshServer rc=0
SftpThread::InitializeSession
SftpThread::InitializeSession Initialized session 
SftpThread::HandshakeSession
SftpThread::HandshakeSession rc=0
SftpThread::GetHostKeyHash
SftpThread::GetHostKeyHash hash=f97613e786118b640fe039eae914a718
SftpThread::GetHostKeyMethod
SftpThread::GetHostKeyMethod method=ssh-rsa
SftpInstance::OnHandshakeFinished
SftpInstance::SendResponseAsStringArray
SftpInstance::SendResponseAsStringArray End
SftpThread::ConnectAndHandshakeImpl End
SftpInstance::HandleMessage
SftpInstance::HandleMessage authenticate 0
SftpInstance::HandleMessage Re-use SftpThread instance
SftpThread::Authenticate
SftpThread::Authenticate Thread started
SftpInstance::HandleMessage End
SftpThread::AuthenticateImpl
SftpThread::AuthenticateUser
SftpThread::AuthenticateUser auth_list=(null)

** Signal 11 from untrusted code: pc=278ca8
[1095:1213:0806/113305:ERROR:nacl_process_host.cc(335)] NaCl process exited with status 62720 (0xf500)

I hope you can help.

**Comment by rfilmyer** [comment]
Hey. I have the exact same error and identical logs as Tjebbe80.

here's the background page console:

```
background.js:1413 Object {type: "mount", serverName: "netshizzle.uk.to", serverPort: "22", authType: "keyboard-interactive", username: "roger"…}authType: "keyboard-interactive"mountPath: ""password: "allah dollaz"privateKey: ""serverName: "netshizzle.uk.to"serverPort: "22"type: "mount"username: "roger"__proto__: Object
background.js:177 mountPath: 
background.js:223 Object {message: "fingerprint", request: 0, values: Array[2]}message: "fingerprint"request: 0values: Array[2]__proto__: Object
background.js:638 Object {requestId: 0, fingerprint: "1033854538007eca173635267b82c623", algorithm: "ssh-rsa"}
background.js:1413 Object {type: "accept", requestId: "0", fileSystemId: "sftpfs://netshizzle.uk.to:22/roger"}
background.js:648 allowToConnect
_generated_background_page.html:1 NativeClient: NaCl module crashed
background.js:233 -1
background.js:721 onNaClModuleCrashed - -1
background.js:1074 doUnmount
background.js:1087 _doUnmount
background.js:1092 sftpfs://netshizzle.uk.to:22/roger
background.js:1303 deleteTaskQueue: sftpfs://netshizzle.uk.to:22/roger
background.js:1343 deleteMetadataCache: sftpfs://netshizzle.uk.to:22/roger
extensions::lastError:133 Unchecked runtime.lastError while running fileSystemProvider.unmount: NOT_FOUND
    at null.<anonymous> (chrome-extension://gbheifiifcfekkamhepkeogobihicgmn/background.js:1093:43)
    at null.<anonymous> (chrome-extension://gbheifiifcfekkamhepkeogobihicgmn/background.js:1134:17)reportIfUnchecked @ extensions::lastError:133handleResponse @ extensions::sendRequest:78
```
And the ui_log:
```
[1061:1061:0826/202418:ERROR:external_cache.cc(109)] ExternalCache cannot find external_crx /var/cache/external_cache/fobcpibfeplaikcclojfdhfdmbbeofai-2.0-23673c2fd52e833b1ce15493c273891d6af0b8c4ec9d031b0f97552285e4c1fc.crx
[1061:1061:0826/203425:ERROR:extension_pref_value_map.cc(74)] NOTREACHED() hit in CanExtensionControlPref. Extension jkghodnilhceideoidjikpgommlajknk is not registered but accesses pref settings.accessibility (incognito: 0). http://crbug.com/454513
[1061:1061:0826/203821:ERROR:extension_pref_value_map.cc(74)] NOTREACHED() hit in CanExtensionControlPref. Extension jkghodnilhceideoidjikpgommlajknk is not registered but accesses pref settings.accessibility (incognito: 0). http://crbug.com/454513
[1061:1061:0826/203908:ERROR:tap_suppression_controller.cc(109)] NOTREACHED() hit in ShouldSuppressTapEnd. Invalid tap end on LAST_CANCEL_STOPPED_FLING state
[413,3059474432:03:46:47.276815] Native Client module will be loaded at base address 0x0000000000000000
SftpInstance::SftpInstance
SftpInstance::SftpInstance End
SftpInstance::HandleMessage
SftpInstance::HandleMessage connect 0
SftpThread::SftpThread
SftpInstance::HandleMessage SftpThread instance created
SftpThread::ConnectAndHandshake
SftpThread::ConnectAndHandshake Thread started
SftpInstance::HandleMessage End
SftpThread::ConnectAndHandshakeImpl
SftpThread::InitializeLibssh2
SftpThread::InitializeLibssh2 rc=0
SftpThread::ConnectToSshServer
SftpThread::ConnectToSshServer sock=3
SftpThread::ConnectToSshServer sockaddr_in ready
SftpThread::ConnectToSshServer rc=0
SftpThread::InitializeSession
SftpThread::InitializeSession Initialized session 
SftpThread::HandshakeSession
SftpThread::HandshakeSession rc=0
SftpThread::GetHostKeyHash
SftpThread::GetHostKeyHash hash=1033854538007eca173635267b82c623
SftpThread::GetHostKeyMethod
SftpThread::GetHostKeyMethod method=ssh-rsa
SftpInstance::OnHandshakeFinished
SftpThread::ConnectAndHandshakeImpl End
SftpInstance::SendResponseAsStringArray
SftpInstance::SendResponseAsStringArray End
SftpInstance::HandleMessage
SftpInstance::HandleMessage authenticate 0
SftpInstance::HandleMessage Re-use SftpThread instance
SftpThread::Authenticate
SftpThread::Authenticate Thread started
SftpInstance::HandleMessage End
SftpThread::AuthenticateImpl
SftpThread::AuthenticateUser
SftpThread::AuthenticateUser auth_list=publickey,keyboard-interactive
SftpThread::AuthenticateByKeyboardInteractive
** abort() called

** Signal 4 from untrusted code: pc=2632b0
[1061:1159:0826/204653:ERROR:nacl_process_host.cc(330)] NaCl process exited with status 64512 (0xfc00)
[425,3059474432:03:46:55.913877] Native Client module will be loaded at base address 0x0000000000000000
```

**Comment by rfilmyer** [comment]
My error only occurred when logging in with `keyboard-interactive` mode. I was able to login using private key successfully.
